/**
 * Friendly display names for common Microsoft 365 SKU part numbers.
 * Source: Microsoft Product names and service plan identifiers for licensing.
 */
const skuFriendlyNames: Record<string, string> = {
  AAD_PREMIUM: "Microsoft Entra ID P1",
  AAD_PREMIUM_P2: "Microsoft Entra ID P2",
  ADALLOM_STANDALONE: "Microsoft Defender for Cloud Apps",
  ATP_ENTERPRISE: "Microsoft Defender for Office 365 (Plan 1)",
  AX7_USER_TRIAL: "Microsoft Dynamics 365 for Finance and Operations",
  BI_AZURE_P0: "Power BI (Free)",
  BI_AZURE_P1: "Power BI Pro",
  BI_AZURE_P2: "Power BI Premium Per User",
  CRMPLAN2: "Dynamics 365 Customer Engagement Plan",
  CRMSTANDARD: "Dynamics 365 for Sales Professional",
  Deskless: "Microsoft 365 F1",
  DYN365_ENTERPRISE_P1_IW: "Dynamics 365 P1 Trial for Information Workers",
  DYN365_ENTERPRISE_PLAN1: "Dynamics 365 Plan 1 Enterprise",
  DYN365_ENTERPRISE_SALES: "Dynamics 365 for Sales Enterprise",
  DYN365_ENTERPRISE_TEAM_MEMBERS: "Dynamics 365 for Team Members",
  DYN365_FINANCIALS_BUSINESS_SKU: "Dynamics 365 for Financials Business",
  ECAL_SERVICES: "ECAL",
  EMS: "Enterprise Mobility + Security E3",
  EMSPREMIUM: "Enterprise Mobility + Security E5",
  ENTERPRISEPACK: "Office 365 E3",
  ENTERPRISEPACKPLUS_FACULTY: "Office 365 A3 for Faculty",
  ENTERPRISEPACKPLUS_STUDENT: "Office 365 A3 for Students",
  ENTERPRISEPREMIUM: "Office 365 E5",
  ENTERPRISEPREMIUM_NOPSTNCONF: "Office 365 E5 (without Audio Conferencing)",
  ENTERPRISEWITHSCAL: "Office 365 E4",
  EQUIVIO_ANALYTICS: "Office 365 Advanced Compliance",
  ERP_TRIAL_INSTANCE: "Dynamics 365 Operations Trial",
  EXCHANGEARCHIVE: "Exchange Online Archiving for Exchange Server",
  EXCHANGEARCHIVE_ADDON: "Exchange Online Archiving for Exchange Online",
  EXCHANGEDESKLESS: "Exchange Online Kiosk",
  EXCHANGEENTERPRISE: "Exchange Online (Plan 2)",
  EXCHANGEESSENTIALS: "Exchange Online Essentials",
  EXCHANGESTANDARD: "Exchange Online (Plan 1)",
  EXCHANGETELCO: "Exchange Online POP",
  EXO_PREMIUM: "Exchange Online Protection Premium",
  FLOW_FREE: "Microsoft Power Automate Free",
  FLOW_P1: "Microsoft Power Automate Plan 1",
  FLOW_PER_USER: "Power Automate per User Plan",
  Forms_Pro_AddOn: "Microsoft Dynamics 365 Customer Voice Additional Responses",
  IDENTITY_THREAT_PROTECTION: "Microsoft 365 E5 Security",
  INFORMATION_PROTECTION_COMPLIANCE: "Microsoft 365 E5 Compliance",
  INTUNE_A: "Microsoft Intune Plan 1",
  INTUNE_SMB: "Microsoft Intune",
  IT_ACADEMY_AD: "Microsoft Imagine Academy",
  LITEPACK: "Office 365 Small Business",
  LITEPACK_P2: "Office 365 Small Business Premium",
  M365_F1: "Microsoft 365 F1",
  M365_F1_COMM: "Microsoft 365 F1",
  MCOEV: "Microsoft Teams Phone Standard",
  MCOEVSMB: "Microsoft Teams Phone Standard (Small and Medium Business)",
  MCOIMP: "Skype for Business Online (Plan 1)",
  MCOMEETADV: "Microsoft 365 Audio Conferencing",
  MCOPSTN1: "Microsoft 365 Domestic Calling Plan",
  MCOPSTN2: "Microsoft 365 Domestic and International Calling Plan",
  MCOPSTN5: "Microsoft 365 Domestic Calling Plan (120 min)",
  MCOPSTNC: "Microsoft 365 Communications Credits",
  MCOSTANDARD: "Skype for Business Online (Plan 2)",
  MDATP_XPLAT: "Microsoft Defender for Endpoint P2",
  MEETING_ROOM: "Microsoft Teams Rooms Standard",
  MICROSOFT_BUSINESS_CENTER: "Microsoft Business Center",
  MICROSOFT_REMOTE_ASSIST: "Microsoft Remote Assist",
  Microsoft_365_Copilot: "Microsoft 365 Copilot",
  MIDSIZEPACK: "Office 365 Midsize Business",
  O365_BUSINESS: "Microsoft 365 Apps for Business",
  O365_BUSINESS_ESSENTIALS: "Microsoft 365 Business Basic",
  O365_BUSINESS_PREMIUM: "Microsoft 365 Business Standard",
  OFFICE365_MULTIGEO: "Multi-Geo Capabilities in Office 365",
  OFFICESUBSCRIPTION: "Microsoft 365 Apps for Enterprise",
  PBI_PREMIUM_P1_ADDON: "Power BI Premium P1",
  PHONESYSTEM_VIRTUALUSER: "Microsoft Teams Phone Resource Account",
  PLANNERSTANDALONE: "Planner Plan 1",
  POWER_BI_ADDON: "Power BI for Office 365 Add-On",
  POWER_BI_INDIVIDUAL_USER: "Power BI",
  POWER_BI_PRO: "Power BI Pro",
  POWER_BI_STANDARD: "Power BI (Free)",
  POWERAPPS_INDIVIDUAL_USER: "PowerApps and Logic Flows",
  POWERAPPS_PER_USER: "Power Apps per User Plan",
  POWERAPPS_VIRAL: "Microsoft Power Apps Plan 2 Trial",
  POWERAUTOMATE_ATTENDED_RPA: "Power Automate per User with Attended RPA Plan",
  POWERFLOW_P2: "Microsoft Power Apps Plan 2",
  PRIVACY_MANAGEMENT_RISK: "Priva Privacy Risk Management",
  PRIVACY_MANAGEMENT_SUB_RIGHTS_REQ: "Priva Subject Rights Request",
  PROJECTCLIENT: "Project for Office 365",
  PROJECTESSENTIALS: "Project Online Essentials",
  PROJECTONLINE_PLAN_1: "Project Online Premium without Project Client",
  PROJECTPREMIUM: "Project Online Premium with Project Client",
  PROJECTPROFESSIONAL: "Project Plan 3",
  RIGHTSMANAGEMENT: "Azure Information Protection Plan 1",
  RIGHTSMANAGEMENT_ADHOC: "Rights Management Adhoc",
  RMS_S_ENTERPRISE: "Azure Information Protection Premium P1",
  SENTINEL: "Microsoft Sentinel",
  SharePoint_Project: "SharePoint Syntex",
  SHAREPOINTENTERPRISE: "SharePoint Online (Plan 2)",
  SHAREPOINTSTANDARD: "SharePoint Online (Plan 1)",
  SHAREPOINTSTORAGE: "Office 365 Extra File Storage",
  SHAREPOINTWAC: "Office Online",
  SMB_APPS: "Microsoft 365 Apps for Business",
  SMB_BUSINESS: "Microsoft 365 Business Basic",
  SMB_BUSINESS_ESSENTIALS: "Microsoft 365 Business Basic",
  SMB_BUSINESS_PREMIUM: "Microsoft 365 Business Premium",
  SPB: "Microsoft 365 Business Premium",
  SPE_E3: "Microsoft 365 E3",
  SPE_E3_USGOV_DOD: "Microsoft 365 E3 (US Government DoD)",
  SPE_E3_USGOV_GCCHIGH: "Microsoft 365 E3 (US Government GCC High)",
  SPE_E5: "Microsoft 365 E5",
  SPE_F1: "Microsoft 365 F3",
  SPZA_IW: "Microsoft PowerApps Plan 2 Trial",
  STANDARDPACK: "Office 365 E1",
  STANDARDWOFFPACK: "Office 365 E2",
  STANDARDWOFFPACK_FACULTY: "Office 365 A1 for Faculty",
  STANDARDWOFFPACK_IW_FACULTY: "Office 365 A1 Plus for Faculty",
  STANDARDWOFFPACK_IW_STUDENT: "Office 365 A1 Plus for Students",
  STANDARDWOFFPACK_STUDENT: "Office 365 A1 for Students",
  STREAM: "Microsoft Stream",
  TEAMS_COMMERCIAL_TRIAL: "Microsoft Teams (Free)",
  TEAMS_ESSENTIALS_AAD: "Microsoft Teams Essentials (Microsoft Entra ID)",
  TEAMS_EXPLORATORY: "Microsoft Teams Exploratory",
  TEAMS_FREE: "Microsoft Teams (Free)",
  THREAT_INTELLIGENCE: "Microsoft Defender for Office 365 (Plan 2)",
  TOPIC_EXPERIENCES: "Viva Topics",
  VISIOCLIENT: "Visio Plan 2",
  VISIOONLINE_PLAN1: "Visio Plan 1",
  VIRTUAL_AGENT_BASE: "Power Virtual Agents",
  WACONEDRIVEENTERPRISE: "OneDrive for Business (Plan 2)",
  WACONEDRIVESTANDARD: "OneDrive for Business (Plan 1)",
  WACSHAREPOINTENT: "Office Online for Enterprise",
  WIN_DEF_ATP: "Microsoft Defender for Endpoint P1",
  WIN10_PRO_ENT_SUB: "Windows 10/11 Enterprise E3",
  WIN10_VDA_E3: "Windows 10/11 Enterprise E3",
  WIN10_VDA_E5: "Windows 10/11 Enterprise E5",
  WINDOWS_STORE: "Windows Store for Business",
  YAMMER_ENTERPRISE: "Yammer Enterprise"
};

export function resolveSkuFriendlyName(skuPartNumber: string): string {
  return skuFriendlyNames[skuPartNumber] ?? skuPartNumber;
}
